exports.Prefix = `R75!`;//your prefix for bot
exports.Token = ``;//your token 
exports.Color = `FFCCBC`;//color   of embed
exports.Ytapi = ``;
exports.Maxplaylistsize = 10;
exports.Staytime = 60;
exports.Volume = 100;
exports.Pruning = false;
exports.Locale = `en`;
exports.Mongo = ``;
exports.admins = [""];
exports.countChannel = "851840956537765938";
